import keyMirror from 'key-mirror'

export default keyMirror({

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  
  TOKEN_REQUEST: null,
  TOKEN_RECEIVED: null,
  TOKEN_FAILURE: null,

  RETRIEVE_DRIVERS_REQUEST: null,
  RETRIEVE_DRIVERS_SUCCESS: null,
  RETRIEVE_DRIVERS_FAILURE: null,

  REGISTER_DRIVERS_REQUEST: null,
  REGISTER_DRIVERS_SUCCESS: null,
  REGISTER_DRIVERS_FAILURE: null,

  RETRIEVE_DRIVER_REQUEST: null,
  RETRIEVE_DRIVER_SUCCESS: null,
  RETRIEVE_DRIVER_FAILURE: null,

  DELETE_DRIVER_REQUEST: null,
  DELETE_DRIVER_SUCCESS: null,
  DELETE_DRIVER_FAILURE: null,
  
  RETRIEVE_ORDERS_REQUEST: null,
  RETRIEVE_ORDERS_SUCCESS: null,
  RETRIEVE_ORDERS_FAILURE: null,
  
  REGISTER_ORDERS_REQUEST: null,
  REGISTER_ORDERS_SUCCESS: null,
  REGISTER_ORDERS_FAILURE: null,
  
  RETRIEVE_ORDER_REQUEST: null,
  RETRIEVE_ORDER_SUCCESS: null,
  RETRIEVE_ORDER_FAILURE: null,
 
  DELETE_ORDER_REQUEST: null,
  DELETE_ORDER_SUCCESS: null,
  DELETE_ORDER_FAILURE: null,
 
  SET_DRIVER_REQUEST: null,
  SET_DRIVER_SUCCESS: null,
  SET_DRIVER_FAILURE: null,

  SET_SCHEDULE_SUCCESS: null,
  SET_SCHEDULE_REQUEST: null,
  SET_SCHEDULE_FAILURE: null,
  
  EDIT_DRIVER_REQUEST: null,
  EDIT_DRIVER_SUCCESS: null,
  EDIT_DRIVER_FAILURE: null,

  REFRESH_STATUS_REQUEST: null,
  REFRESH_STATUS_SUCCESS: null,
  REFRESH_STATUS_FAILURE: null,

})

export const STATUS_NEW = "Ожидает исполнителя"
export const STATUS_WAIT = "wait for accepting"
export const STATUS_ACTIVE = "in process"
export const STATUS_EXECUTED = "completed"
